FROM python:3.14-slim

RUN pip install uv

WORKDIR /app

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-install-project --group test

COPY . .
RUN uv sync --frozen --group test

CMD ["uv", "run", "--group", "test", "pytest"]
