"""
auth sessions, retired refresh tokens, activity log

Revision ID: 967a1e31f6c2
Revises: 4eda5e32e411
Create Date: 2026-08-28 23:49:26.036508

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "967a1e31f6c2"
down_revision: str | Sequence[str] | None = "4eda5e32e411"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activitylog",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("ip_address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_index(
        op.f("ix_activitylog_created_by_id"), "activitylog", ["created_by_id"], unique=False
    )
    op.create_table(
        "usersession",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("refresh_token_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ip_address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_agent", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("device_fingerprint", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "delivery_mode",
            sa.Enum("json", "cookie", name="tokendelivery"),
            server_default="json",
            nullable=False,
        ),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_index(
        op.f("ix_usersession_device_fingerprint"),
        "usersession",
        ["device_fingerprint"],
        unique=False,
    )
    op.create_index(op.f("ix_usersession_user_id"), "usersession", ["user_id"], unique=False)
    op.create_table(
        "retiredrefreshtoken",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["usersession.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_index(
        op.f("ix_retiredrefreshtoken_session_id"),
        "retiredrefreshtoken",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_retiredrefreshtoken_token_hash"),
        "retiredrefreshtoken",
        ["token_hash"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_retiredrefreshtoken_token_hash"), table_name="retiredrefreshtoken")
    op.drop_index(op.f("ix_retiredrefreshtoken_session_id"), table_name="retiredrefreshtoken")
    op.drop_table("retiredrefreshtoken")
    op.drop_index(op.f("ix_usersession_user_id"), table_name="usersession")
    op.drop_index(op.f("ix_usersession_device_fingerprint"), table_name="usersession")
    op.drop_table("usersession")
    op.drop_index(op.f("ix_activitylog_created_by_id"), table_name="activitylog")
    op.drop_table("activitylog")
    # ### end Alembic commands ###
