"""
courier credentials, check requests and provider results

Revision ID: f93ae9faba50
Revises: ac19fe629213
Create Date: 2026-08-30 12:34:55.390563

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f93ae9faba50"
down_revision: str | Sequence[str] | None = "ac19fe629213"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "checkrequest",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("phone_normalized", sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
        sa.Column(
            "source",
            sa.Enum("web", "api", "bulk", "order", name="checksource"),
            server_default="web",
            nullable=False,
        ),
        sa.Column("risk_score", sa.Float(), nullable=True),
        sa.Column("risk_band", sa.Enum("low", "medium", "high", name="riskband"), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_index(
        "ix_check_request_user_created_at",
        "checkrequest",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_check_request_user_phone", "checkrequest", ["user_id", "phone_normalized"], unique=False
    )
    op.create_table(
        "couriercredential",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "provider", sa.Enum("pathao", "steadfast", "redx", name="providerenum"), nullable=False
        ),
        sa.Column("username_encrypted", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password_encrypted", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("key_version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("untested", "valid", "invalid", name="credentialstatus"),
            server_default="untested",
            nullable=False,
        ),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_index(
        op.f("ix_couriercredential_user_id"), "couriercredential", ["user_id"], unique=False
    )
    op.create_index(
        "uq_courier_credential_active_user_provider",
        "couriercredential",
        ["user_id", "provider"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "providerresult",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("check_request_id", sa.Integer(), nullable=False),
        sa.Column(
            "provider", sa.Enum("pathao", "steadfast", "redx", name="providerenum"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("ok", "unavailable", "auth_failed", "timeout", name="providerstatus"),
            nullable=False,
        ),
        sa.Column("total_orders", sa.Integer(), nullable=True),
        sa.Column("delivered", sa.Integer(), nullable=True),
        sa.Column("returned", sa.Integer(), nullable=True),
        sa.Column("cancelled", sa.Integer(), nullable=True),
        sa.Column("customer_rating", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column(
            "error_code",
            sa.Enum(
                "no_credential",
                "circuit_open",
                "token_wait_timeout",
                "auth_failed",
                "timeout",
                "parse_error",
                "provider_error",
                name="providererrorcode",
            ),
            nullable=True,
        ),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["check_request_id"], ["checkrequest.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_index(
        op.f("ix_providerresult_check_request_id"),
        "providerresult",
        ["check_request_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_providerresult_check_request_id"), table_name="providerresult")
    op.drop_table("providerresult")
    op.drop_index(
        "uq_courier_credential_active_user_provider",
        table_name="couriercredential",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_index(op.f("ix_couriercredential_user_id"), table_name="couriercredential")
    op.drop_table("couriercredential")
    op.drop_index("ix_check_request_user_phone", table_name="checkrequest")
    op.drop_index("ix_check_request_user_created_at", table_name="checkrequest")
    op.drop_table("checkrequest")
    # ### end Alembic commands ###
